// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Task_Test.WebUI.Entity
{
    public partial class City
    {
       

        public int Id { get; set; }
        [StringLength(30)]
        public string Name { get; set; }

       
    }
}