// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Task_Test.WebUI.Entity
{
    public partial class MainDbContext : DbContext
    {
        public MainDbContext()
        {
        }

        public MainDbContext(DbContextOptions<MainDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Category> Category { get; set; }
       
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Arrival> Arrivals { get; set; }
        public virtual  DbSet<Departrue> Departrues { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

       
    }
}