// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Task_Test.WebUI.Entity
{
    public partial class Product
    {
        public int Id { get; set; }
        [StringLength(30)]
        public string Name { get; set; }
        public int? Stok { get; set; }
        public int? Kg { get; set; }
        public DateTime? Datetime { get; set; }
       
        public int? CategoryId { get; set; }
        public virtual Category Category { get; set; }

        

        public int ArrivalId { get; set; }
        public virtual Arrival Arrival { get; set; }

       
        public int Departrueid { get; set; }
        public virtual Departrue Departrue { get; set; }


    }
}